name: Deploy Finder Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      with: 
        script:
          cd /var/www/finder.fjobeir.com/html/backend
          git pull origin main
          npm install --production
          pm2 restart node-app
